# Generated by Django 2.2.1 on 2019-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile1', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='filldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.IntegerField()),
                ('unique_HR', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], default='Male', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('self_employed', models.CharField(default='Under Investigation', max_length=100)),
                ('family_history', models.CharField(default='NaN', max_length=100)),
                ('treatment', models.CharField(default='NaN', max_length=100)),
                ('work_interfere', models.CharField(default='NaN', max_length=100)),
                ('no_employees', models.CharField(default='NaN', max_length=100)),
                ('remote_work', models.CharField(default='NaN', max_length=100)),
                ('tech_company', models.CharField(default='NaN', max_length=100)),
                ('benefits', models.CharField(default='NaN', max_length=100)),
                ('care_options', models.CharField(default='NaN', max_length=100)),
                ('wellness_program', models.CharField(default='NaN', max_length=100)),
                ('seek_help', models.CharField(default='NaN', max_length=100)),
                ('anonimity', models.CharField(default='NaN', max_length=100)),
                ('leave', models.CharField(default='NaN', max_length=100)),
                ('mental_health_consequence', models.CharField(default='NaN', max_length=100)),
                ('phys_health_consequence', models.CharField(default='NaN', max_length=100)),
                ('coworkers', models.CharField(default='NaN', max_length=100)),
                ('supervisor', models.CharField(default='NaN', max_length=100)),
                ('mental_health_interview', models.CharField(default='NaN', max_length=100)),
                ('phys_health_interview', models.CharField(default='NaN', max_length=100)),
                ('mental_vs_physical', models.CharField(default='NaN', max_length=100)),
                ('obs_consequence', models.CharField(default='NaN', max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
